### ISSUE TITLE
Interface enhancements

### ISSUE THREAD

**Issue by malobre** [async-graphql/async-graphql#138] opened 2020-06-02 09:28 UTC
Why are GraphQL interfaces represented by rust enums and not traits ?

This doesn't seems very idiomatic:
```rust
use ::uuid::Uuid;

#[Interface(
    field(name = "id", type = "&Uuid")
    )]
pub enum Node {
    User(User)
}

pub struct User {
    pub id: Uuid,
}

#[::async_graphql::Object]
impl User {
    pub async fn id(&self) -> &Uuid {
        &self.id
    }
}
```

Something like this would be easier to understand:
```rust
use ::uuid::Uuid;

#[::async_graphql::Interface]
#[::async_trait::async_trait]
pub trait Node {
    async fn id(&self) -> &Uuid;
}

pub struct User {
    pub id: Uuid,
}

#[::async_graphql::Object]
#[::async_trait::async_trait]
impl Node for User {
    async fn id(&self) -> &Uuid {
        &self.id
    }
}
```

Note that the `async_trait` crate is needed as async trait functions are not currently supported.

**Comment by sunli829** [comment] 2020-06-02 13:04
Because of procedural macro limitations, I have no way of knowing that `User` implements `Node`.

**Comment by phated** [comment] 2020-06-02 22:01
@sunli829 I've been thinking a lot about this. Could we support Trait interfaces like this:

```rust
#[::async_graphql::Interface]
pub trait Node {
    async fn id(&self) -> i32;
}

pub struct User {
    pub id: i32,
}

#[::async_graphql::Implements]
impl Node for User {
    async fn id(&self) -> i32 {
        self.id
    }
}
```

If we use 2 separate macros, I think we could use a pattern like is used in https://github.com/hainish/multi-default-trait-impl

Do you think this would work?

**Comment by sunli829** [comment] 2020-06-02 23:03
Actually, this is already implemented in #42, but there are other problems, and I'll keep thinking about this for a few days. 😁

**Comment by phated** [comment] 2020-06-02 23:09
@sunli829 please let me know if I can help in any way. This is a feature I would love to have!

**Comment by sunli829** [comment] 2020-06-02 23:27
The hardest part is to return an array that implements a particular interface object.

```rust
#[Object]
impl Query {
    async fn my_obj(&self) -> Vec<NodeInterface<???>> {
         vec![MyObjA.into(), MyObjB.into()]
    }
}
```

I think maybe we can solve it in the following way:

```rust
#[Object]
impl Query {
    async fn my_obj(&self) -> NodeInterfaceArray {
         NodeInterfaceArray.append(MyObjA).append(MyObjB)
    }
}
```

`NodeInterfaceArray` is an array that can hold different types.

**Comment by sunli829** [comment] 2020-06-02 23:33
I'll try again today, and I'll let you know if I need any help.😀 @phated

**Comment by phated** [comment] 2020-06-02 23:33
@sunli829 can `Vec< >` not contain an `impl Foo` type?

**Comment by sunli829** [comment] 2020-06-02 23:36
No, rust doesn't support this, because impl Foo may have different types and different memory layouts and can't be in the same Vec.

Just like the following does not compile through.

```rust
vec![1i32, 2i64]
```

**Comment by sunli829** [comment] 2020-06-02 23:40
And trait objects lose type information, so they don't work either.

```rust
Vec<dyn Foo>
```

**Comment by phated** [comment] 2020-06-02 23:46
@sunli829 I figured it out! This is the types required:

```rust
struct Query;

trait Foo {}

struct MyObjA;
impl Foo for MyObjA {}

struct MyObjB;
impl Foo for MyObjB {}

impl Query {
    async fn my_obj(&self) -> Vec<Box<dyn Foo>> {
        vec![Box::new(MyObjA), Box::new(MyObjB)]
    }
}

fn main() {
    let query = Query {};
}
```

https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

**Comment by sunli829** [comment] 2020-06-02 23:51
> @sunli829 I figured it out! This is the types required:
> 
> ```rust
> struct Query;
> 
> trait Foo {}
> 
> struct MyObjA;
> impl Foo for MyObjA {}
> 
> struct MyObjB;
> impl Foo for MyObjB {}
> 
> impl Query {
>     async fn my_obj(&self) -> Vec<Box<dyn Foo>> {
>         vec![Box::new(MyObjA), Box::new(MyObjB)]
>     }
> }
> 
> fn main() {
>     let query = Query {};
> }
> ```
> 
> https://doc.rust-lang.org/edition-guide/rust-2018/trait-system/dyn-trait-for-trait-objects.html

No, the trait object can't solve the problem, it causes the loss of type information. 
The problem is more complicated than it looks. 😂

**Comment by phated** [comment] 2020-06-02 23:53
> The problem is more complicated than it looks

I believe you, and I want to understand more completely.

> it causes the loss of type information

Can you show where the type information is needed and cannot be accessed if you Box it?

**Comment by sunli829** [comment] 2020-06-02 23:57
```rust
i32::type_name()                       =======>    Int
Box<dyn Foo>::type_name()              =======>    ???
```

You can see how `juniper` defines the interface, which is similar to `async-graphql` but more complex to use.

**Comment by phated** [comment] 2020-06-03 00:01
🤔 

@sunli829 in your example what happens if we unbox the `dyn Foo` with `*`?

**Comment by sunli829** [comment] 2020-06-03 00:01
The only thing I can think of at this point is to use the following code to solve this problem, and of course, I think the final implementation can look clearer.

```rust
NodeInterfaceArray.append(MyObjA).append(MyObjB)
```

The definition of `NodeInterfaceArray` is similar to `VisitorCons`.

**Comment by sunli829** [comment] 2020-06-03 00:03
> 🤔
> 
> @sunli829 in your example what happens if we unbox the `dyn Foo` with `*`?

`Async-graphql` is type-safe because it is based on rust generics, and trait objects are very much like dynamic types, which are completely incompatible with the existing architecture.

**Comment by sunli829** [comment] 2020-06-03 00:10
If the function inside the trait is not &self, then it cannot be a trait object.
The following code cannot be compiled.

```rust
trait A {
    fn test() -> i32;
}

fn main() {
    let a: dyn A = todo!();
}
```

**Comment by phated** [comment] 2020-06-03 00:14
> If the function inside the trait has no self argument, then it cannot be a trait object.
The following code cannot be compiled.

Oh, okay. Your example is the same as: https://doc.rust-lang.org/1.8.0/book/trait-objects.html#object-safety ?

**Comment by sunli829** [comment] 2020-06-03 00:20
Yes. 😄

**Comment by sunli829** [comment] 2020-06-03 04:32
I've been trying all morning and I can't make it happen...

Type `Node<MyObjA , Node<MyObjB, Nil>>` doesn't meet the requirements. It's static type.

```rust
#[Object]
impl Query {
    async fn my_obj(&self) -> Node<MyObjA, Node<MyObjB, Nil>> {
         NodeInterfaceArray.append(MyObjA).append(MyObjB)
    }
}
```

**Comment by sunli829** [comment] 2020-06-03 04:33
By far, I think the current interface definition is the best solution.

**Comment by Amareis** [comment] 2020-06-03 10:56
Does it possible to split Interface in two parts? First is defining all needed methods as trait and second - is attaching it to some enum?

```rust

#[InterfaceDefinition]
trait IChatDef {
    async fn messages(&self) -> Vec<Message>;
}

#[Interface(trait=IChatDef)]
enum IChat {
    PM(PMChat),
    Group(GroupChat),
}
```

**Comment by Amareis** [comment] 2020-06-03 11:00
Also this can solve naming issues of interface fields, we can just reuse `field` attribute on trait methods. And trait can even provide default methods implementation, which is really good for reusing code. Under the hood `IntefaceDefinition` can use async-trait and so on.

**Comment by sunli829** [comment] 2020-06-03 11:17
I think it can be done. @Amareis @phated @malobre 

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}
```

**Comment by sunli829** [comment] 2020-06-03 11:56
Need to add a definition to PMChat. 🙁

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

#[Object(implement(IChat))]
struct PMChat { ... }

#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}
```

**Comment by Amareis** [comment] 2020-06-03 12:05
Maybe just attach #[Object] to `impl IChat for PMChat`? If PMChat will be `Object` to, it should work.

**Comment by sunli829** [comment] 2020-06-03 12:23
If the `#[Object]` does not know which interfaces the object implements, the `message` method needs to be implemented twice.

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

struct PMChat;

impl IChat for PMChat {
    async fn messages(&self) -> Vec<Message> { ... }
}

#[Object]
impl PMChat {
    async fn messages(&self) -> Vec<Message> { ... }
}

#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}
```

**Comment by Amareis** [comment] 2020-06-03 12:24
Why just don't
```rust
#[Object]
impl IChat for PMChat {
    async fn messages(&self) -> Vec<Message> { ... }
}
```
?

**Comment by sunli829** [comment] 2020-06-03 12:26
PMChat also has its own fields.

**Comment by sunli829** [comment] 2020-06-03 12:27
What do you mean?

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

struct PMChat;

#[Object]
impl IChat for PMChat {
    async fn messages(&self) -> Vec<Message> { ... }
}

#[Object]
impl PMChat {
    async fn id(&self) -> i32 { ... }
}

#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}
```

**Comment by Amareis** [comment] 2020-06-03 12:27
Hmm. `Object` doesn't support multiple impl per type?
```rust
#[Object]
impl IChat for PMChat {
    async fn messages(&self) -> Vec<Message> { ... }
}

#[Object]
impl PMChat {
    async fn title(&self) -> &String { ... }
}
```

**Comment by sunli829** [comment] 2020-06-03 12:29
This `#[Object]` still doesn't know that PMChat implements IChat.

```rust
#[Object]
impl PMChat {
    async fn id(&self) -> i32 { ... }
}
```

**Comment by sunli829** [comment] 2020-06-03 12:51
I'm sure this can be done.

```rust
#[Interface(objects(PMChat, GroupChat))]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

impl IChat for PMChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}

#[Object]
impl PMChat  {
    async fn id(&self) -> i32 { ... }
}
```

**Comment by malobre** [comment] 2020-06-03 12:53
What about using `Any` ?

```rust
trait Node {
    fn id(&self) -> i32;
}

struct User;

impl Node for User {
    fn id(&self) -> i32 { todo!() }
}

struct File;

impl Node for File {
    fn id(&self) -> i32 { todo!() }
}

fn getNodeById(id: i32) -> &'static dyn ::std::any::Any {
    //--snip--
}

fn main() {
    let node = getNodeById(0);
    
    if let Some(user) = node.downcast_ref::<User>() {
        todo!();
    } else if let Some(file) = node.downcast_ref::<File>() {
        todo!();
    }
}
```

**Comment by sunli829** [comment] 2020-06-03 12:54
No, Any is a trait object.A

**Comment by sunli829** [comment] 2020-06-03 13:00
This is the solution I can think of, but it still has some problems.The final code I generated turned `IChat` into an enum, probably `IChatImpl`, but IChat is still a trait.
It creates a new type that the IDE cannot recognize.
And when the resolver function returns an interface, the interface type is `IChatImpl`.

```
#[Interface(objects(PMChat, GroupChat))]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

impl IChat for PMChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}

#[Object]
impl PMChat  {
    async fn id(&self) -> i32 { ... }
}

struct Query;

#[Object]
impl Query {
    async fn chats(&self) -> Vec<IChatImpl> { ... }
}
```

**Comment by Amareis** [comment] 2020-06-03 13:14
> ```rust
> #[Interface(objects(PMChat, GroupChat))]
> trait IChat {
>     async fn messages(&self) -> Vec<Message>;
> }
> 
> impl IChat for PMChat  {
>     async fn messages(&self) -> Vec<Message>{ ... }
> }
> 
> #[Object]
> impl PMChat  {
>     async fn id(&self) -> i32 { ... }
> }
> ```

Oh, that's sweet!

I dig into `Object` macro and understood your position. I think way with explicit enum and explicit implementaitions list in main `Object` is good enough. But also if it's possible to use InterfaceImpl it was be great!

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

#[InterfaceImpl(IChat)] //here is magic???
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}

#[Object]
impl PMChat  {
    async fn id(&self) -> i32 { ... }
}

#[Object] //I don't know if macro needed here
impl IChat for PMChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}


#[Object]
impl GroupChat  {
    async fn id(&self) -> i32 { ... }
    async fn title(&self) -> &String { ... }
}

#[Object] //I don't know if macro needed here
impl IChat for GroupChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}
```

or

```rust
#[Interface]
trait IChat {
    async fn messages(&self) -> Vec<Message>;
}

#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
    Group(GroupChat),
}

#[Object(impl(IChat))]
impl PMChat  {
    async fn id(&self) -> i32 { ... }
}

#[Object] //I don't know if macro needed here
impl IChat for PMChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}


#[Object(impl(IChat))]
impl GroupChat  {
    async fn id(&self) -> i32 { ... }
    async fn title(&self) -> &String { ... }
}

#[Object] //I don't know if macro needed here
impl IChat for GroupChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}
```

**Comment by sunli829** [comment] 2020-06-03 13:23
The bottom line is that I have to put the trait definition together with what objects support the trait so I can generate the right code.

**Comment by sunli829** [comment] 2020-06-03 13:27
This doesn't support features like Guard, Input Validator, etc., so I still think the existing implementation of function forwarding is the best and the easiest to use.

**Comment by malobre** [comment] 2020-06-03 13:31
Yes but you can downcast internally and do whatever you need. However this might be a bad idea performance wise.

What about this:
```rust
fn get_node_by_id(id: i32) -> impl Node + Type { // This allows to access required methods
    //--snip--
}
```

**Comment by Amareis** [comment] 2020-06-03 13:35
Hmm. Why? I think it's totally possible.
```rust
//generates hidden type with resolve_fields method, which name is based on trait and type
//all guards and input validators are acting like in normal object 
#[ObjectInterfaceImpl]
impl IChat for PMChat  {
    async fn messages(&self) -> Vec<Message>{ ... }
}

//in resolve_fields delegates fields resolving to generated type with known name
#[Object(impl(IChat))]
impl PMChat  {
    async fn id(&self) -> i32 { ... }
}
```

**Comment by sunli829** [comment] 2020-06-03 13:41
> > No, Any is a trait object.
> 
> Yes but you can downcast internally and do whatever you need. However this might be a bad idea performance wise.
> 
> What about this:
> 
> ```rust
> fn get_node_by_id(id: i32) -> impl Node + Type { // This allows to access required methods
>     //--snip--
> }
> ```

In fact, this is no different from enum, I need to know which objects implement Interface. 😀

**Comment by sunli829** [comment] 2020-06-03 13:46
> Hmm. Why? I think it's totally possible.
> 
> ```rust
> //generates hidden type with resolve_fields method, which name is based on trait and type
> //all guards and input validators are acting like in normal object 
> #[ObjectInterfaceImpl]
> impl IChat for PMChat  {
>     async fn messages(&self) -> Vec<Message>{ ... }
> }
> 
> //in resolve_fields delegates fields resolving to generated type with known name
> #[Object(impl(IChat))]
> impl PMChat  {
>     async fn id(&self) -> i32 { ... }
> }
> ```

It works, but there is no type safety, and `PMChat` can be compiled, even if it does not implement the fields defined in `IChat`.

**Comment by malobre** [comment] 2020-06-03 13:49
> 
> 
> > > No, Any is a trait object.
> > 
> > 
> > Yes but you can downcast internally and do whatever you need. However this might be a bad idea performance wise.
> > What about this:
> > ```rust
> > fn get_node_by_id(id: i32) -> impl Node + Type { // This allows to access required methods
> >     //--snip--
> > }
> > ```
> 
> In fact, this is no different from enum, I need to know which objects implement Interface. 😀

Ok I see.
Could we create a global variable (with `lazy_static` or similar) and store which object implement which interface there ?

```rust
trait Interface {...}

struct A;

#[Object] // Add A to the list
impl Interface for A {...}

struct B;

#[Object] // Add B to the list
impl Interface for B {...}
```

**Comment by Amareis** [comment] 2020-06-03 13:52
>PMChat can be compiled, even if it does not implement the fields defined in IChat
Hmm. I think it should be checked in InterfaceImpl. It can generate some empty types, which will be just type guards.

**Comment by sunli829** [comment] 2020-06-03 14:02
> > > > No, Any is a trait object.
> > > 
> > > 
> > > Yes but you can downcast internally and do whatever you need. However this might be a bad idea performance wise.
> > > What about this:
> > > ```rust
> > > fn get_node_by_id(id: i32) -> impl Node + Type { // This allows to access required methods
> > >     //--snip--
> > > }
> > > ```
> > 
> > 
> > In fact, this is no different from enum, I need to know which objects implement Interface. 😀
> 
> Ok I see.
> Could we create a global variable (with `lazy_static` or similar) and store which object implement which interface there ?
> 
> ```rust
> trait Interface {...}
> 
> struct A;
> 
> #[Object] // Add A to the list
> impl Interface for A {...}
> 
> struct B;
> 
> #[Object] // Add B to the list
> impl Interface for B {...}
> ```

Yes, that's easy, but that's runtime information, and generating the code needs to be done at compile time.

**Comment by sunli829** [comment] 2020-06-03 14:04
> > PMChat can be compiled, even if it does not implement the fields defined in IChat
> 
> Hmm. I think it should be checked in InterfaceImpl (or Object itself?..). It can generate some empty types, which will be just type guards.

You mean there is no real IChat? It's just a type guards, so let me think about that first.

**Comment by Amareis** [comment] 2020-06-03 14:23
No-no, real IChat keep going. There is simple chain: `ObjectInterfaceImpl` generate phatom type, which implements `ObjectType` for given trait implementation. `Object(impl(IChat))` generate code, which a) calls that phantom type to resolve trait fields and b) checks that PMChat implements trait IChat (e.g., just creates unused function `fn check(a: PMChat) {&a as &IChat}).

**Comment by malobre** [comment] 2020-06-03 14:25
> Yes, that's easy, but that's runtime information, and generating the code needs to be done at compile time.

I meant doing it at compile time during macro-expansion.
Unfortunately this doesn't seem possible for now, see https://github.com/rust-lang/rust/issues/44034.

**Comment by sunli829** [comment] 2020-06-03 14:29
Can you provide a minimum implementation after expanding procedural macros? 😂

**Comment by Amareis** [comment] 2020-06-03 14:35
Uh-oh, let's try :)

**Comment by sunli829** [comment] 2020-06-03 14:36
> > Yes, that's easy, but that's runtime information, and generating the code needs to be done at compile time.
> 
> I meant doing it at compile time during macro-expansion.
> Unfortunately this doesn't seem possible for now, see [rust-lang/rust#44034](https://github.com/rust-lang/rust/issues/44034).

Yes. 😃

**Comment by Amareis** [comment] 2020-06-03 15:54
Ok, there is simple standalone (and sync) example. It's completely type safe (rust check traits implementations for us) and full static, there is no single dynamic dispatching. It can be easily combined with `field` macro attribute in interface trait definition. I don't know if it possible to combine with traits default methods combinations (it's definitely possible with https://stackoverflow.com/a/56311216/5576420).

```rust
#![allow(non_camel_case_types, dead_code)]

#[derive(Debug)]
enum Value {
    Int(i32),
    Boolean(bool),
}

//simple sync mockup of ObjectType
trait ObjType {
    fn resolve_field(&self, field_name: String) -> Result<Value, ()>;
}

//#[Interface]
trait IChat {
    fn id(&self) -> i32;
}

struct PMChat;

//in resolve_fields delegates fields resolving to generated type with known name
//#[Object(impl(IChat))]
impl PMChat  {
    fn is_activated(&self) -> bool { true }
}

//generated
impl ObjType for PMChat {
    fn resolve_field(&self, field_name: String) -> Result<Value, ()> {
        if field_name == "is_activated" {
            return Ok(Value::Boolean(self.is_activated()));
        }

        //we can construct unique trait name from macro arguments
        if let Ok(res) = IChat_PMChat_ObjectInterfaceImpl::resolve_field(self, field_name) {
            return Ok(res);
        }
        //there can be another interfaces resolving

        Err(())
    }
}


//generates hidden type with resolve_fields method, which name is based on trait and type
//all guards and input validators are acting like in normal object
//#[ObjectInterfaceImpl]
impl IChat for PMChat  {
    fn id(&self) -> i32 { 1 }
}

//generated
//since we know type name (PMChat) and interface name (IChat)
//we can construct unique trait name
trait IChat_PMChat_ObjectInterfaceImpl {
    fn resolve_field(&self, field_name: String) -> Result<Value, ()>;
}

impl IChat_PMChat_ObjectInterfaceImpl for PMChat {
    //method name also can be unique
    fn resolve_field(&self, field_name: String) -> Result<Value, ()> {
        if field_name == "id" {
            return Ok(Value::Int(self.id()));
        }

        Err(())
    }
}

//#[InterfaceImpl(IChat)]
enum IChatImpl {
    PM(PMChat),
}

//generated, checks that all generated traits is existing
//if this struct compiles, all traits are implemented,
//since single correct way to construct phantom trait is ObjectInterfaceImpl macro,
//called on trait implementation for struct
struct check_IChat_impls(dyn IChat_PMChat_ObjectInterfaceImpl/*, dyn anotherTrait...*/);

fn main() {
    let c = PMChat;
    dbg!(ObjType::resolve_field(&c, "id".to_string()).unwrap());
    dbg!(ObjType::resolve_field(&c, "is_activated".to_string()).unwrap());
}
```

**Comment by Amareis** [comment] 2020-06-03 18:13
Also, I think this approach can be used to collect fields from SimpleObject too (#35).

**Comment by Amareis** [comment] 2020-06-03 18:57
Even more, I feel that if push this approach to the limit, we can get rid off async-trait completely! But that's not for sure.

**Comment by sunli829** [comment] 2020-06-04 01:38
> Ok, there is simple standalone (and sync) example. It's completely type safe (rust check traits implementations for us) and full static, there is no single dynamic dispatching. It can be easily combined with `field` macro attribute in interface trait definition. I don't know if it possible to combine with traits default methods implementations (it's definitely possible with https://stackoverflow.com/a/56311216/5576420).
> 
> ```rust
> #![allow(non_camel_case_types, dead_code)]
> 
> #[derive(Debug)]
> enum Value {
>     Int(i32),
>     Boolean(bool),
> }
> 
> //simple sync mockup of ObjectType
> trait ObjType {
>     fn resolve_field(&self, field_name: String) -> Result<Value, ()>;
> }
> 
> //#[Interface]
> trait IChat {
>     fn id(&self) -> i32;
> }
> 
> struct PMChat;
> 
> //in resolve_fields delegates fields resolving to generated type with known name
> //#[Object(impl(IChat))]
> impl PMChat  {
>     fn is_activated(&self) -> bool { true }
> }
> 
> //generated
> impl ObjType for PMChat {
>     fn resolve_field(&self, field_name: String) -> Result<Value, ()> {
>         if field_name == "is_activated" {
>             return Ok(Value::Boolean(self.is_activated()));
>         }
> 
>         //we can construct unique trait name from macro arguments
>         if let Ok(res) = IChat_PMChat_ObjectInterfaceImpl::resolve_field(self, field_name) {
>             return Ok(res);
>         }
>         //there can be another interfaces resolving
> 
>         Err(())
>     }
> }
> 
> 
> //generates hidden type with resolve_fields method, which name is based on trait and type
> //all guards and input validators are acting like in normal object
> //#[ObjectInterfaceImpl]
> impl IChat for PMChat  {
>     fn id(&self) -> i32 { 1 }
> }
> 
> //generated
> //since we know type name (PMChat) and interface name (IChat)
> //we can construct unique trait name
> trait IChat_PMChat_ObjectInterfaceImpl {
>     fn resolve_field(&self, field_name: String) -> Result<Value, ()>;
> }
> 
> impl IChat_PMChat_ObjectInterfaceImpl for PMChat {
>     //method name also can be unique
>     fn resolve_field(&self, field_name: String) -> Result<Value, ()> {
>         if field_name == "id" {
>             return Ok(Value::Int(self.id()));
>         }
> 
>         Err(())
>     }
> }
> 
> //#[InterfaceImpl(IChat)]
> enum IChatImpl {
>     PM(PMChat),
> }
> 
> //generated, checks that all generated traits is existing
> //if this struct compiles, all traits are implemented,
> //since single correct way to construct phantom trait is ObjectInterfaceImpl macro,
> //called on trait implementation for struct
> struct check_IChat_impls(dyn IChat_PMChat_ObjectInterfaceImpl/*, dyn anotherTrait...*/);
> 
> fn main() {
>     let c = PMChat;
>     dbg!(ObjType::resolve_field(&c, "id".to_string()).unwrap());
>     dbg!(ObjType::resolve_field(&c, "is_activated".to_string()).unwrap());
> }
> ```

 It seems feasible, but I don't think it's any better than the current implementation. 😁

**Comment by Amareis** [comment] 2020-06-04 12:08
Hmmm... Second variant is use only trait with dynamic dispatching (`get_concrete_type` and `IChatVars` is generated):

```rust
//#[Interface(objects(PMChat, GroupChat))]
trait IChat {
    fn id(&self) -> i32;

    fn get_concrete_type(&self) -> IChatVars {
        unimplemented!();
    }
}

#[derive(Debug)]
enum IChatVars<'a> {
    PMChat(&'a PMChat),
    GroupChat(&'a GroupChat),
}

#[derive(Debug)]
struct PMChat;

//#[Object(impl(IChat))]
impl PMChat  {
    fn is_activated(&self) -> bool { true }
}

//#[InterfaceImpl]
impl IChat for PMChat  {
    fn id(&self) -> i32 {1}

    fn get_concrete_type(&self) -> IChatVars {
        IChatVars::PMChat(self)
    }
}

#[derive(Debug)]
struct GroupChat;

//#[Object(impl(IChat))]
impl GroupChat  {
    fn users_count(&self) -> i32 { 5 }
}

//#[InterfaceImpl]
impl IChat for GroupChat  {
    fn id(&self) -> i32 {2}

    fn get_concrete_type(&self) -> IChatVars {
        IChatVars::GroupChat(self)
    }
}

#[derive(Debug)]
struct Query;

//#[Object]
impl Query {
    fn chats(&self) -> Vec<Box<dyn IChat>> {
        vec![Box::new(PMChat), Box::new(PMChat), Box::new(GroupChat)]
    }
}

fn main() {
    let q = Query;
    for c in q.chats() {
        dbg!(c.get_concrete_type());
    }
}
```

**Comment by Amareis** [comment] 2020-06-04 12:37
I think it's most idiomatic approach for rust. Additionally full static variant can be added.

**Comment by sunli829** [comment] 2020-06-04 12:42
I'll think about it. 😀

**Closed** 2020-06-29 05:38 UTC
