### ISSUE TITLE
Nested input types generate an error at introspection time

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#880] opened 2022-03-29 14:56 UTC
I have some types like this:

```rust
#[derive(InputObject)]
pub(super) struct EditDomainInput {
    domain: String,
    title: Option<String>,
    name: Option<String>,
    description: Option<String>,
    logo: Option<String>,
    contact_info: Option<ContactInfo>,
}

#[derive(InputObject)]
pub struct ContactInfo {
    address: Option<Address>,
    phone_number: Option<String>,
    payment_url: Option<String>,
    contact_email: Option<String>,
}

#[derive(InputObject)]
pub struct Address {
    country: Option<String>,
    region: Option<String>,
    city: Option<String>,
    postal_code: Option<String>,
    street_address: Option<String>,
}
```

This compiles fine and I can generate SDL  from it.

## Expected Behavior

Introspection queries against this schema should work.

## Actual Behavior

Introspection query fails; error from GraphiQL:

> `Introspection must provide input type for arguments, but received: ContactInfo.`

## Specifications

- Version: 3.0.36
- Platform: macOS
- Subsystem: input  types

**Comment by sunli829** [comment] 2022-03-30 02:58
I can't reproduce it, can you provide a repository that reproduces this issue? 😁

**Comment by djc** [comment] 2022-03-30 10:50
Here's a full reproducer: https://github.com/djc/nested-input.

What I find really surprising about this is that introspection works okay as long as I comment out the `_input` argument to the `_edit_foo()` mutation.

**Comment by sunli829** [comment] 2022-03-30 11:40
`Info` is both an input type and an output type causing this error.

```rust
#[derive(InputObject)]
#[graphql(name = "InfoInput")] // Add this attribute to rename the input type name
pub struct Info {
    email: Option<String>,
}
```

**Comment by sunli829** [comment] 2022-03-30 11:41
This error cannot currently be reported at compile time, I will add a runtime check. 🙂

**Comment by djc** [comment] 2022-03-30 11:48
Why can't Rust types implement both the input and the output traits?

**Comment by sunli829** [comment] 2022-03-30 11:48
This is not allowed in the GraphQL spec, they need to have different names.

**Comment by sunli829** [comment] 2022-03-30 11:49
You can implement as input object and output object for the same Rust type, but for GraphQL they are actually different objects, so must have different names as well.

**Comment by djc** [comment] 2022-03-30 11:50
Would be nice if there was a way to do this similar to the way currently multiple names can be declared depending on any generic type parameters.

**Comment by sunli829** [comment] 2022-03-30 11:51
This should not be possible. 😂

**Comment by sunli829** [comment] 2022-03-30 11:53
Or I don't know how to do it. 😄

**Comment by sunli829** [comment] 2022-03-30 12:12
Yes, procedural macros can do it.

**Comment by sunli829** [comment] 2022-03-30 12:15
You mean, always automatically add the `Input` suffix?

**Comment by djc** [comment] 2022-03-30 12:23
Ah, sorry -- I didn't actually mean that the macros should implicitly add a suffix to input type names. I meant that there should be a way for me to reuse the same type under a different name, but it looks like that already exists.

I think it might actually be nice if there was a way I could opt in to add `Input` suffixes to all input type names on a per-crate basis to prevent this issue from happening, but I could understand that you might not want to enable this by default.

**Comment by sunli829** [comment] 2022-03-30 12:25
Well, I'm now going to add a runtime check that panics when the same Rust type has the same name.

**Comment by sunli829** [comment] 2022-03-30 13:07
Released in `v3.0.37`

**Closed** 2022-04-11 14:17 UTC
Labels: bug
