### ISSUE TITLE
future cannot be sent between threads safely

### ISSUE THREAD

**Issue by sail-sail** [async-graphql/async-graphql#558] opened 2021-07-01 01:20 UTC
```
future cannot be sent between threads safely
the trait `std::marker::Send` is not implemented for `(dyn ResponseError + 'static)`
required for the cast to the object type `dyn std::future::Future<Output = std::result::Result<std::option::Option<async_graphql::Value>, ServerError>> + std::marker::Send`rustc
usr_graphql.rs(41, 14): future is not `Send` as this value is used across an await
```

**Comment by sunli829** [comment] 2021-07-01 02:41
This is not a problem caused by `async-graphql`, so I will close this issue. If you can give a code snippet, I will be happy to help you solve it.

**Closed** 2021-07-01 02:41 UTC
Labels: question
