### ISSUE TITLE
Make it possible to parametrize Context with my own type

### ISSUE THREAD

**Issue by djc** [async-graphql/async-graphql#904] opened 2022-04-28 08:17 UTC
## Description of the feature

Currently you can store data in an `async_graphql::Context` only inside a type map. However, this means you have to get that data out by passing in the type and checking if it's actually there every time. It would be better if the `Context` passed in to resolvers could be parametrized with an application-specific context type, which can be retrieved directly from a method. This way, it would be statically provable to the compiler that the required context is in there, saving a whole lot of unnecessary error handling code.

## Code example (if possible)

```rust
    async fn edit_post(
        &self,
        cx: &gql::Context<'_>,
        input: EditPostInput,
    ) -> Result<PostEdge, Error> {
        let app = match cx.data::<Arc<App>>() {
            Ok(app) => app,
            Err(_) => return Err(Error::internal("application context missing")),
        };
```

should become something like

```rust
    async fn edit_post(
        &self,
        cx: &gql::Context<'_, App>,
        input: EditPostInput,
    ) -> Result<PostEdge, Error> {
        let app = cx.app();
```

**Comment by sunli829** [comment] 2022-04-29 10:43
I understand, this adds a generic parameter and brings more complexity, but it does avoid some errors at compile time, just that `async-graphql` was designed that way from the beginning. 🙂

**Comment by sunli829** [comment] 2022-04-29 10:50
This generic parameter seems to be related only to `Context`, but in fact it will be infected everywhere.

**Comment by djc** [comment] 2022-07-28 08:50
Fair enough, I've added some abstractions around our use of the `Context` to make this less painful.

**Closed** 2022-07-28 08:50 UTC
Labels: enhancement

**Comment by frederikhors** [comment] 2022-09-23 10:15
> Fair enough, I've added some abstractions around our use of the `Context` to make this less painful.

Do you mind write an example of your "abstractions"?

**Comment by djc** [comment] 2022-09-23 19:54
@frederikhors we created an extension trait, roughly like this:

```rust
trait AppContext {
    fn foo(&self) -> &Foo;
}

impl AppContext for async_graphql::Context<'_> {
    fn foo(&self) -> &Foo {
        // Our POST handler always stores a `Foo`, so this should never panic
        self.data::<Foo>().unwrap()
    }
}
```

In our case, this definition is scoped in a module where all GraphQL requests are routed through a single HTTP handler, so this is fairly easy to verify as statically safe.
